/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sections = {
  _id: string
  _type: 'sections'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sections?: Array<
    {
      _key: string
    } & Section
  >
}

export type Section = {
  _type: 'section'
  name?:
    | 'overview'
    | 'power architecture'
    | 'superstructure'
    | 'control'
    | 'propulsion'
    | 'body'
    | 'water & heating systems'
    | 'outfitting & interior'
  slug?: Slug
  articles?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'article'
  }>
}

export type Annotation = {
  _id: string
  _type: 'annotation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  note?: string
  system?:
    | 'overview'
    | 'power architecture'
    | 'superstructure'
    | 'control'
    | 'propulsion'
    | 'body'
    | 'water & heating systems'
    | 'outfitting & interior'
  position?: {
    x?: number
    y?: number
    z?: number
  }
  related?: Array<string>
  relatedModels?: Array<string>
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  role?: string
}

export type Material = {
  _id: string
  _type: 'material'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  aka?: Array<string>
}

export type Component = {
  _id: string
  _type: 'component'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  componentPart?: string
  link?: {
    url?: string
    label?: string
  }
  slug?: Slug
  scale?: '10m' | '1m' | '0.1m'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  count?: number
  materials?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'material'
  }>
  specs?: Array<{
    key?: string
    value?: string
    unit?: 'cm' | 'lb' | 'in' | 'mm' | 'V' | 'W'
    _type: 'spec'
    _key: string
  }>
  model?:
    | 'POWER ARCHITECTURE::SIMPLIFIED BATT RACKS'
    | 'POWER ARCHITECTURE::SOLAR::SIMPLIFIED SP'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::MPPT250/70-Tr solar charge controller'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::IMO-2108 4 string - DC disconnect'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::ELCON HK-J 6.6KW charger'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::victron lynx distributor'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::COTEK SP-3000 (3000W) inverter'
    | 'POWER ARCHITECTURE::ELEC BOARD COMPONENTS::Orion 360W isolated DC-DC converter'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::Miniature Bayonet T3 1/4 Bulb & holder'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::AC rotary switch'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::30amp inlet'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::50amp inlet'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::sensors'
    | 'POWER ARCHITECTURE::SMARTPLUG INLET SYSTEM::breakers'
    | 'SUPERSTRUCTURE::instr panel & wireway::IP 1/2" StarBoard'
    | 'SUPERSTRUCTURE::instr panel & wireway::IP 1" X 1" X 1/8" alum angle (8982K4)'
    | 'SUPERSTRUCTURE::instr panel & wireway::IP 1" X 1 1/2" X 1/8" alum angle (8982K87)'
    | 'SUPERSTRUCTURE::instr panel & wireway::rmvbl panels material TBD'
    | 'SUPERSTRUCTURE::WIREWAYS::ww parts surfs::thru-collars ORANGE'
    | 'SUPERSTRUCTURE::WIREWAYS::ww parts surfs::int-ext penetrations PINK'
    | 'SUPERSTRUCTURE::WIREWAYS::ww parts surfs::int-int penetrations GREEN'
    | 'SUPERSTRUCTURE::WINDOWS::window panes'
    | 'SUPERSTRUCTURE::WINDOWS::rough window hardware & trim::window trim surfs'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::DECK ACCESS STAIRLADDER::SL 1/4" 6061 tread plate'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::DECK ACCESS STAIRLADDER::SL 1/4" 5052 alum'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::DECK ACCESS STAIRLADDER::SL nom. 1" SCH40 pipe alum'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::DECK ACCESS STAIRLADDER::g10 backing pl'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::TOE-KICKS::TK 1/4" FHMS'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::TOE-KICKS::TOE-KICK SURFS'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::TOE-KICKS::TOE-KICK FLANGES'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::flat bar base::5" X 3/8" baseplate surfs'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::flat bar base::G10 backing plates'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::flat bar base::3/8" 316L SS bolts'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FRAMING::1.5" SQ TUBE'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FRAMING::1" X 2" TUBE'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FRAMING::4" SQ TUBE'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FRAMING::OTHER SIZES & MISC'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::PLATING'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::RAILINGS & POSTS::railing flanges'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::RAILINGS & POSTS::SCH40 1" nominal'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::RAILINGS & POSTS::SCH40 2" nominal'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FASCIA::fascia plates'
    | 'SUPERSTRUCTURE::ALUM. PARTS+::FASCIA::fascia flange brackets'
    | 'CONTROL::STEERING::STEERING SHELVES::P&S rudder shelf'
    | 'CONTROL::STEERING::STEERING SHELVES::port dummy shelf'
    | 'CONTROL::STEERING::steering tunnels'
    | 'CONTROL::STEERING::STEERING COMPONENTS::tillers & draglinks'
    | 'CONTROL::STEERING::STEERING COMPONENTS::JEFA 5T050'
    | 'CONTROL::STEERING::STEERING COMPONENTS::JEFA 5T050ZS'
    | 'CONTROL::STEERING::STEERING COMPONENTS::hand tiller stbd'
    | 'CONTROL::STEERING::STEERING COMPONENTS::autopilot DD1'
    | 'CONTROL::STEERING::STEERING COMPONENTS::Washer, delrin \xF850,5 x \xF8110 x 4,5mm'
    | 'CONTROL::STEERING::STEERING COMPONENTS::locking rings part no. 46040-46054'
    | 'CONTROL::STEERING::STEERING COMPONENTS::50mm dummy shafts'
    | 'PROPULSION::SIMPLIFIED propeller & strut'
    | 'PROPULSION::SHAFTLINE COMPONENTS::Cutless Bearing brass "Bale" size'
    | 'PROPULSION::SHAFTLINE COMPONENTS::PSS shaft seal 02-100-200'
    | 'PROPULSION::SHAFTLINE COMPONENTS::stern tube 2" OD X 1.5" ID GRP source from fisheries supply'
    | 'PROPULSION::SHAFTLINE COMPONENTS::shaft::surfs'
    | 'PROPULSION::rudder assembly::foil top wedge contoured'
    | 'PROPULSION::rudder assembly::rudder shaft & foil'
    | 'PROPULSION::rudder assembly::Turcite bushings'
    | 'PROPULSION::rudder assembly::SS thrust bearing, polished top'
    | 'PROPULSION::rudder assembly::SS sleeve'
    | 'PROPULSION::rudder assembly::Rudder tube::G10 tube 3" OD X 2.75" ID'
    | 'PROPULSION::rudder assembly::Rudder tube::Molded tube ends for turc bushings'
    | 'PROPULSION::MOTOR MOUNT::MM surfs'
    | 'PROPULSION::20W Bell Marine Motor::SIMPLIFIED 20W Bell surfs'
    | 'PROPULSION::20W Bell Marine Motor::MOTOR CONTROLLER APPROX.'
    | 'BODY::HULLS & DECKS::MESH H&D (for website)::MESH HULL'
    | 'BODY::HULLS & DECKS::MESH H&D (for website)::MESH DECK'
    | 'BODY::HULLS & DECKS::HATCHES::aft steering hatches'
    | 'BODY::HULLS & DECKS::PORTLIGHTS::portlight surfs'
    | 'BODY::HULLS & DECKS::PORTLIGHTS::portlight cut-out edge'
    | 'BODY::CTR BEAM::scuppers'
    | 'BODY::CTR BEAM::fwd beam hatches (approx)'
    | 'BODY::CTR BEAM::ctr beam outside surfaces'
    | 'BODY::CTR BEAM::ctr beam inside surfaces'
    | 'BODY::CTR BEAM::ctr beam console bhd'
    | 'BODY::INTERNALS::4" ID wireway tubes'
    | 'BODY::INTERNALS::soles & bhds'
    | 'BODY::INTERNALS::stringers'
    | 'WATER/HEATING SYSTEMS::KEEL COOLERS::KC surfs'
    | 'WATER/HEATING SYSTEMS::Headhunter Royal Flush Espresso'
    | 'WATER/HEATING SYSTEMS::dehumidifer'
    | 'WATER/HEATING SYSTEMS::heat pump'
    | 'WATER/HEATING SYSTEMS::HEAT PUMP VENTS & INTAKES'
    | 'WATER/HEATING SYSTEMS::TANKS::hot water tank (model?)'
    | 'WATER/HEATING SYSTEMS::TANKS::holding tank 25 gal TOD 85-1532WH'
    | 'WATER/HEATING SYSTEMS::TANKS::port FW tank (35 gal) Todd MFG #:85-1525WH'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::1/2" acrylic'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::HDPE guide & coaming'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::CH other materials'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::MF-02-110-60'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::SIMPLIFIED TRACK HARDWARE'
    | 'OUTFITTING/INTERIOR::COMPANIONWAY HATCH::6061 sq tube'
    | 'OUTFITTING/INTERIOR::"ugly corner" options::small corner box'
    | 'OUTFITTING/INTERIOR::BATTERY CMPT::8667K18_Flame-Retardant Garolite G-10-FR4 Sheet'
    | 'OUTFITTING/INTERIOR::BATTERY CMPT::access panel WRK::access panel surfs'
    | 'OUTFITTING/INTERIOR::BATTERY CMPT::access panel WRK::angle flanges (on panel)'
    | 'OUTFITTING/INTERIOR::BATTERY CMPT::access panel WRK::coaming (scribed to hull)'
    | 'OUTFITTING/INTERIOR::BATTERY CMPT::wiring conduit::2x2 2"x2" array'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::CABINETS::cabinet surfaces'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::CABINETS::WM CABINET::36" long version approx/ summer 2025'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::CTR BEAM TABLE'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::SHELF SURFS'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::GALLEY SURFS'
    | 'OUTFITTING/INTERIOR::galley, workbench, shelving, etc.::workbench V2'
    | 'OUTFITTING/INTERIOR::Isotherm Drawer 55 \u2013 Frost Free Freezer'
    | 'OUTFITTING/INTERIOR::Isotherm Drawer 65 - FROST FREE Refrigerator'
    | 'OUTFITTING/INTERIOR::SHOWER AFT STBD::approx parts locs'
    | 'OUTFITTING/INTERIOR::SHOWER AFT STBD::potential hose thru-deck locs'
    | 'OUTFITTING/INTERIOR::INT. FURNISHING::dbl mattress'
    | 'OUTFITTING/INTERIOR::portland pudgy::PP SIMPLIFIED'
    | 'OUTFITTING/INTERIOR::cleats'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::EXT. INSTR. MOUNTS::EIM V4 (4" sq tube)'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::EXT. INSTR. MOUNTS::EIM V4 (4" sq tube)::EIMV4 antenna'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::EXT. INSTR. MOUNTS::FWD MAST & MOUNTS'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::Simrad HALO20+ Radar'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::Signal Mate LED Anchor Light'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::Furuno SCX-20 satellite compass'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::FLIR MD-625'
    | 'OUTFITTING/INTERIOR::EXT. INSTRUMENTS::Searchlight D-SS PRO Driving Pod'
    | 'OUTFITTING/INTERIOR::helm seat'
    | 'OUTFITTING/INTERIOR::SIMPLIFIED ANCHOR WINCH'
    | 'OUTFITTING/INTERIOR::SIMPLIFIED CTR DECK TRACKS'
    | 'OUTFITTING/INTERIOR::fwd trampoline & beam ROUGH'
  documentation?: Array<
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
        }
        media?: unknown
        _type: 'documentation'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | {
        url?: string
        label?: string
        _type: 'link'
        _key: string
      }
  >
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  slug?: Slug
  authors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  relatedModels?: Array<string>
  content?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'person'
            }
        >
        style?: 'normal' | 'h2'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'child'
        _key: string
      }
    | {
        title?: string
        caption?: string
        imageSet?: Array<
          | {
              drawing?: string
              _type: 'drawingImage'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'imageSet'
        _key: string
      }
    | {
        fullBleed?: boolean
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        _type: 'inlineImage'
        _key: string
      }
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Sections
  | Section
  | Annotation
  | Person
  | Material
  | Component
  | Article
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
