/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sections = {
  _id: string
  _type: 'sections'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sections?: Array<
    {
      _key: string
    } & Section
  >
}

export type Section = {
  _type: 'section'
  name?:
    | 'overview'
    | 'power architecture'
    | 'superstructure'
    | 'control'
    | 'propulsion'
    | 'body'
    | 'water & heating systems'
    | 'outfitting & interior'
  slug?: Slug
  articles?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'article'
  }>
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  role?: string
}

export type Material = {
  _type: 'material'
  name?:
    | 'Acrylic'
    | 'Alum 5052'
    | 'Alum 6061'
    | 'Alum AlMgSi1'
    | 'Aluminum'
    | 'Brass'
    | 'Bronze'
    | 'Carbon Fiber'
    | 'Carbon Fiber Plywood Sandwich'
    | 'Composite Sandwich'
    | 'Composite Sandwich (HULL)'
    | 'Composite Sandwich (INTERNALS)'
    | 'Delrin'
    | 'Fiberglass'
    | 'Particle Board'
    | 'Plastic'
    | 'Plywood'
    | 'Solar Panels'
    | 'Stainless Steel'
    | 'Starboard (HDPE)'
    | 'Trampoline'
    | 'Turcite'
    | 'Windows & Portlights'
    | 'Wood'
  description?: string
}

export type Materials = {
  _id: string
  _type: 'materials'
  _createdAt: string
  _updatedAt: string
  _rev: string
  materials?: Array<
    {
      _key: string
    } & Material
  >
}

export type Component = {
  _id: string
  _type: 'component'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  componentPart?: string
  relatedModel?: string
  slug?: Slug
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  location?: {
    lat?: number
    lng?: number
  }
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  isLive?: boolean
  subtitle?: string
  slug?: Slug
  authors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  relatedModels?: Array<string>
  content?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'person'
            }
        >
        style?: 'normal' | 'h2'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'child'
        _key: string
      }
    | {
        title?: string
        caption?: string
        imageSet?: Array<
          | {
              drawing?: string
              _type: 'drawingImage'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'imageSet'
        _key: string
      }
    | {
        fullBleed?: boolean
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        _type: 'inlineImage'
        _key: string
      }
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Sections
  | Section
  | Slug
  | Person
  | Material
  | Materials
  | Component
  | SanityImageCrop
  | SanityImageHotspot
  | Location
  | Article
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
