/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Systems = {
  _id: string
  _type: 'systems'
  _createdAt: string
  _updatedAt: string
  _rev: string
  systems?: Array<
    {
      _key: string
    } & System
  >
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type System = {
  _type: 'system'
  name?:
    | 'overview'
    | 'power architecture'
    | 'superstructure'
    | 'control'
    | 'propulsion'
    | 'body'
    | 'water & heating systems'
    | 'outfitting & interior'
  slug?: Slug
  articles?: Array<
    {
      _key: string
    } & ArticleReference
  >
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  role?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  slug?: Slug
  affiliations?: Array<{
    label?: string
    url?: string
    _type: 'link'
    _key: string
  }>
}

export type Material = {
  _type: 'material'
  name?:
    | 'Acrylic'
    | 'Aluminum'
    | 'Aluminum 5052'
    | 'Aluminum 6061'
    | 'Aluminum AlMgSi1'
    | 'Bronze'
    | 'Carbon Fiber'
    | 'Composite Sandwich'
    | 'Composite Sandwich (HULL)'
    | 'Composite Sandwich (INTERNALS)'
    | 'Delrin'
    | 'Fiberglass'
    | 'Glass'
    | 'Naval Brass'
    | 'Particle Board'
    | 'Plastic'
    | 'Plywood'
    | 'Solar Panels'
    | 'Stainless Steel'
    | 'Starboard (HDPE)'
    | 'Turcite'
    | 'Wood'
  description?: string
}

export type Materials = {
  _id: string
  _type: 'materials'
  _createdAt: string
  _updatedAt: string
  _rev: string
  materials?: Array<
    {
      _key: string
    } & Material
  >
}

export type Component = {
  _id: string
  _type: 'component'
  _createdAt: string
  _updatedAt: string
  _rev: string
  relatedModel?: string
  title?: string
  componentPart?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  location?: {
    lat?: number
    lng?: number
  }
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  isLive?: boolean
  hideMaterials?: boolean
  subtitle?: string
  slug?: Slug
  authors?: Array<
    {
      _key: string
    } & PersonReference
  >
  content?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | ({
              _key: string
            } & PersonReference)
        >
        style?: 'normal' | 'h2'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              href?: string
              _type: 'link'
              _key: string
            }
          | {
              reference?: ArticleReference
              _type: 'internalLink'
              _key: string
            }
        >
        level?: number
        _type: 'child'
        _key: string
      }
    | {
        title?: string
        caption?: string
        imageSet?: Array<
          | {
              drawing?: string
              _type: 'drawingImage'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'imageSet'
        _key: string
      }
    | {
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        _type: 'inlineImage'
        _key: string
      }
    | {
        title?: string
        models?: Array<string>
        _type: 'inlineModel'
        _key: string
      }
    | {
        title?: string
        type?: 'range chart'
        _type: 'chart'
        _key: string
      }
  >
  relatedModels?: Array<string>
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | Systems
  | ArticleReference
  | System
  | Slug
  | Person
  | Material
  | Materials
  | Component
  | Location
  | PersonReference
  | Article
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
